package com.ecommerce.payment.domain

import java.util.UUID

/** Identifier of a payment attempt, generated by the payment service; the `paymentId` of the payment events. */
@JvmInline
value class PaymentAttemptId(
    val value: UUID,
) {
    override fun toString(): String = value.toString()
}

/** Identifier of a refund record, generated by the payment service. */
@JvmInline
value class RefundId(
    val value: UUID,
) {
    override fun toString(): String = value.toString()
}

/** Identifier of an order of the order context (stored as a reference, never a foreign key). */
@JvmInline
value class OrderId(
    val value: UUID,
) {
    override fun toString(): String = value.toString()
}

/** Identifier of an account of the identity context: the owner of the order. */
@JvmInline
value class AccountId(
    val value: UUID,
) {
    override fun toString(): String = value.toString()
}

/**
 * Client-generated key of one logical charge or refund request (`Idempotency-Key`, a UUID). The order service uses
 * the checkout key as the charge key, so the synchronous charge and the `OrderPlaced` consumer converge.
 */
@JvmInline
value class IdempotencyKey(
    val value: UUID,
) {
    override fun toString(): String = value.toString()

    companion object {
        private const val REFUND_NAMESPACE = "payment:refund-of-order:"
        private const val RETRY_NAMESPACE = "payment:retry-of:"

        /**
         * The key of the refund that an `OrderCancelled` event triggers for [orderId]: derived from the order, so a
         * redelivered or replayed cancellation converges on the same refund.
         */
        fun refundOf(orderId: OrderId): IdempotencyKey =
            IdempotencyKey(UUID.nameUUIDFromBytes((REFUND_NAMESPACE + orderId).toByteArray(Charsets.UTF_8)))

        /**
         * The key of the retry of the attempt keyed [previous]: derived from it, so the checkout key stays on the
         * first attempt only and every attempt of the chain keeps a key of its own.
         */
        fun retryOf(previous: IdempotencyKey): IdempotencyKey =
            IdempotencyKey(UUID.nameUUIDFromBytes((RETRY_NAMESPACE + previous).toByteArray(Charsets.UTF_8)))
    }
}
