-- Order context schema (data-model section 3.4). Ids are generated by the services; no foreign keys to other
-- contexts. Business records are never deleted; idempotency records expire after 24 hours.

CREATE TABLE orders (
    id                   uuid        PRIMARY KEY,
    order_number         text        NOT NULL UNIQUE,
    account_id           uuid        NOT NULL,
    -- Set on AccountDeleted: the order is kept under this pseudonym (FR-007).
    account_pseudonym    text        NULL,
    order_status         text        NOT NULL,
    payment_status       text        NOT NULL,
    cancellation_reason  text        NULL,
    cancelled_at         timestamptz NULL,
    cancelled_by         text        NULL,
    decline_category     text        NULL,
    total_minor          bigint      NOT NULL CHECK (total_minor > 0),
    currency             char(3)     NOT NULL,
    -- Delivery address snapshot (personal data; scrubbed once a deleted account's order is terminal).
    recipient_name       text        NOT NULL,
    address_line1        text        NOT NULL,
    address_line2        text        NULL,
    city                 text        NOT NULL,
    region               text        NULL,
    postal_code          text        NOT NULL,
    country              char(2)     NOT NULL,
    -- Recipient snapshot carried by the order events (personal data).
    recipient_email      text        NOT NULL,
    recipient_phone      text        NULL,
    recipient_channels   text        NOT NULL,
    payment_method_ref   text        NOT NULL,
    idempotency_key      uuid        NOT NULL,
    reservation_id       uuid        NOT NULL,
    payment_attempt_id   uuid        NULL,
    paid_at              timestamptz NULL,
    payment_expires_at   timestamptz NULL,
    refund_id            uuid        NULL,
    refund_recorded_at   timestamptz NULL,
    placed_at            timestamptz NOT NULL,
    version              bigint      NOT NULL,
    CONSTRAINT orders_cancellation_iff_cancelled
        CHECK ((cancellation_reason IS NOT NULL) = (order_status = 'cancelled')),
    CONSTRAINT orders_fulfilment_is_paid
        CHECK (order_status NOT IN ('preparing', 'shipped', 'delivered') OR payment_status = 'approved')
);

CREATE INDEX orders_account_placed_idx ON orders (account_id, placed_at DESC, id DESC);
CREATE INDEX orders_pending_payment_idx ON orders (payment_expires_at) WHERE payment_status = 'pending';

CREATE TABLE order_lines (
    order_id         uuid    NOT NULL REFERENCES orders (id),
    position         int     NOT NULL,
    product_id       uuid    NOT NULL,
    sku              text    NOT NULL,
    name             text    NOT NULL,
    unit_price_minor bigint  NOT NULL CHECK (unit_price_minor >= 0),
    currency         char(3) NOT NULL,
    quantity         int     NOT NULL CHECK (quantity BETWEEN 1 AND 99),
    PRIMARY KEY (order_id, position)
);

-- Append-only history of both statuses.
CREATE TABLE status_changes (
    order_id    uuid        NOT NULL REFERENCES orders (id),
    position    int         NOT NULL,
    kind        text        NOT NULL CHECK (kind IN ('order', 'payment')),
    from_status text        NULL,
    to_status   text        NOT NULL,
    changed_at  timestamptz NOT NULL,
    changed_by  text        NOT NULL,
    reason      text        NULL,
    PRIMARY KEY (order_id, position)
);

-- One checkout attempt per (account, key): the claim of a running request (no response yet) or the stored answer.
CREATE TABLE idempotency_records (
    account_id      uuid        NOT NULL,
    idempotency_key uuid        NOT NULL,
    request_hash    text        NOT NULL,
    order_id        uuid        NULL,
    response_status int         NULL,
    response_body   text        NULL,
    created_at      timestamptz NOT NULL,
    expires_at      timestamptz NOT NULL,
    PRIMARY KEY (account_id, idempotency_key)
);

CREATE INDEX idempotency_records_expires_idx ON idempotency_records (expires_at);

-- ORD-<yyyyMMdd>-<sequence>: one counter per UTC day.
CREATE TABLE order_number_sequences (
    day        date   PRIMARY KEY,
    last_value bigint NOT NULL
);
