package com.ecommerce.order.domain

import java.util.UUID

/** Identifier of an order, generated by the order service (data-model section 1). */
@JvmInline
value class OrderId(
    val value: UUID,
) {
    override fun toString(): String = value.toString()
}

/** Identifier of an account of the identity context (the token subject). */
@JvmInline
value class AccountId(
    val value: UUID,
) {
    override fun toString(): String = value.toString()
}

/** Identifier of a catalogue product. */
@JvmInline
value class ProductId(
    val value: UUID,
) {
    override fun toString(): String = value.toString()
}

/** Identifier of a saved delivery address of an account (identity context). */
@JvmInline
value class AddressId(
    val value: UUID,
) {
    override fun toString(): String = value.toString()
}

/** Identifier of the stock reservation the catalogue holds for an order. */
@JvmInline
value class ReservationId(
    val value: UUID,
) {
    override fun toString(): String = value.toString()
}

/** Identifier of a charge attempt of the payment context (`paymentId` of the payment events). */
@JvmInline
value class PaymentAttemptId(
    val value: UUID,
) {
    override fun toString(): String = value.toString()
}

/** Identifier of a refund recorded by the payment context. */
@JvmInline
value class RefundId(
    val value: UUID,
) {
    override fun toString(): String = value.toString()
}

/** Client-generated key of one checkout attempt (`Idempotency-Key`, a UUID), reused as the charge key. */
@JvmInline
value class IdempotencyKey(
    val value: UUID,
) {
    override fun toString(): String = value.toString()
}
