-- Payment context schema (data-model section 3.5). Ids are generated by the service; orders and accounts are
-- references to other contexts, never foreign keys. Business records are never deleted. No card data is stored:
-- payment_method_ref is the opaque token of the simulated provider (Principle III).

CREATE TABLE payment_attempts (
    id                 uuid        PRIMARY KEY,
    order_id           uuid        NOT NULL,
    account_id         uuid        NOT NULL,
    kind               text        NOT NULL CHECK (kind = 'charge'),
    amount_minor       bigint      NOT NULL CHECK (amount_minor > 0),
    currency           char(3)     NOT NULL,
    payment_method_ref text        NOT NULL,
    outcome            text        NOT NULL CHECK (outcome IN ('approved', 'declined', 'pending')),
    decline_category   text        NULL,
    provider_reference text        NULL CHECK (char_length(provider_reference) BETWEEN 1 AND 64),
    -- The Idempotency-Key of the request (the checkout key for charges made by the order service).
    idempotency_key    uuid        NOT NULL,
    created_at         timestamptz NOT NULL,
    CONSTRAINT payment_attempts_idempotency_key_unique UNIQUE (idempotency_key),
    CONSTRAINT payment_attempts_category_iff_declined
        CHECK ((decline_category IS NOT NULL) = (outcome = 'declined')),
    CONSTRAINT payment_attempts_reference_unless_pending
        CHECK ((provider_reference IS NULL) = (outcome = 'pending'))
);

-- At most one approved charge per order (FR-013), whatever the key.
CREATE UNIQUE INDEX payment_attempts_one_approved_charge_idx
    ON payment_attempts (order_id) WHERE kind = 'charge' AND outcome = 'approved';

CREATE INDEX payment_attempts_order_idx ON payment_attempts (order_id, created_at DESC, id DESC);

CREATE TABLE refunds (
    id                 uuid        PRIMARY KEY,
    order_id           uuid        NOT NULL,
    account_id         uuid        NOT NULL,
    -- The refunded charge: one refund per charge, so one per cancellation (MVP: full refunds only).
    attempt_id         uuid        NOT NULL REFERENCES payment_attempts (id),
    amount_minor       bigint      NOT NULL CHECK (amount_minor > 0),
    currency           char(3)     NOT NULL,
    status             text        NOT NULL CHECK (status = 'recorded'),
    provider_reference text        NOT NULL CHECK (char_length(provider_reference) BETWEEN 1 AND 64),
    idempotency_key    uuid        NOT NULL,
    created_at         timestamptz NOT NULL,
    -- When RefundRecorded was published; null while the owner's contact snapshot is not known yet.
    announced_at       timestamptz NULL,
    CONSTRAINT refunds_idempotency_key_unique UNIQUE (idempotency_key),
    CONSTRAINT refunds_one_per_charge UNIQUE (attempt_id)
);

CREATE INDEX refunds_order_idx ON refunds (order_id, created_at DESC, id DESC);
