#!/usr/bin/env node
// Generates the typed API surface of the storefront from the OpenAPI contracts (constitution VII:
// API clients are typed from the contract; hand-written response types are forbidden).
//
//   node scripts/generate-api.mjs            regenerate src/api/generated/*.d.ts (git-ignored)
//   node scripts/generate-api.mjs --check    exit 1 when any generated file is missing or stale
//   node scripts/generate-api.mjs --ensure   generate only when a file is missing (used before
//                                            lint, test and build so a fresh clone works)
//
// Quiet on success (Principle VIII): nothing is printed unless something is wrong.
import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';

const here = path.dirname(fileURLToPath(import.meta.url));
const frontendRoot = path.resolve(here, '..');
const repositoryRoot = path.resolve(frontendRoot, '..');
const outputDir = path.join(frontendRoot, 'src', 'api', 'generated');

const platformContracts = path.join(
  repositoryRoot,
  'specs',
  '004-ecommerce-platform-mvp',
  'contracts',
  'openapi',
);
const storefrontContracts = path.join(
  repositoryRoot,
  'specs',
  '005-storefront-dev-bootstrap',
  'contracts',
  'openapi',
);

/** @type {ReadonlyArray<{ name: string, source: string }>} */
const inputs = [
  { name: 'identity', source: path.join(platformContracts, 'identity.yaml') },
  { name: 'catalog', source: path.join(platformContracts, 'catalog.yaml') },
  { name: 'cart', source: path.join(platformContracts, 'cart.yaml') },
  { name: 'order', source: path.join(platformContracts, 'order.yaml') },
  { name: 'payment', source: path.join(platformContracts, 'payment.yaml') },
  {
    name: 'gateway-browser-session',
    source: path.join(storefrontContracts, 'gateway-browser-session.yaml'),
  },
  { name: 'telemetry', source: path.join(storefrontContracts, 'telemetry.yaml') },
];

const header = (relativeSource) =>
  [
    '/*',
    ' * Generated by scripts/generate-api.mjs from ' + relativeSource + '.',
    ' * Do not edit: run `npm run generate` instead. Hand-written response types are forbidden.',
    ' */',
    '',
  ].join('\n');

async function render(input) {
  const ast = await openapiTS(new URL('file://' + input.source), {
    exportType: true,
    rootTypes: false,
    silent: true,
  });
  const relativeSource = path.relative(repositoryRoot, input.source);
  return header(relativeSource) + astToString(ast);
}

function outputPath(input) {
  return path.join(outputDir, input.name + '.d.ts');
}

async function currentContent(file) {
  if (!existsSync(file)) return undefined;
  return readFile(file, 'utf8');
}

async function generateAll({ onlyMissing }) {
  await mkdir(outputDir, { recursive: true });
  for (const input of inputs) {
    const target = outputPath(input);
    if (onlyMissing && existsSync(target)) continue;
    await writeFile(target, await render(input), 'utf8');
  }
}

async function check() {
  const stale = [];
  for (const input of inputs) {
    const expected = await render(input);
    const actual = await currentContent(outputPath(input));
    if (actual !== expected) stale.push(path.relative(frontendRoot, outputPath(input)));
  }
  if (stale.length > 0) {
    process.stderr.write(
      'generated API types are missing or stale (run `npm run generate`):\n  ' +
        stale.join('\n  ') +
        '\n',
    );
    process.exitCode = 1;
  }
}

const mode = process.argv[2] ?? '';
try {
  if (mode === '--check') await check();
  else if (mode === '--ensure') await generateAll({ onlyMissing: true });
  else if (mode === '') await generateAll({ onlyMissing: false });
  else {
    process.stderr.write('usage: generate-api.mjs [--check|--ensure]\n');
    process.exitCode = 2;
  }
} catch (error) {
  process.stderr.write(
    'generate-api: ' + (error instanceof Error ? error.message : String(error)) + '\n',
  );
  process.exitCode = 1;
}
